# -*- coding: utf-8 -*-
"""public api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_h0ZcX3ck5vyS4nL5uCUNZ9fiRB8gOo
"""

!pip install requests pandas matplotlib

import requests
import pandas as pd
import matplotlib.pyplot as plt

url = "https://api.open-meteo.com/v1/forecast"
params = {
    "latitude": 28.6139,
    "longitude": 77.2090,
    "hourly": "temperature_2m",
}

response = requests.get(url, params=params)
data = response.json()
data

df = pd.DataFrame({
    "time": data["hourly"]["time"],
    "temperature": data["hourly"]["temperature_2m"]
})

df.head()

df["time"] = pd.to_datetime(df["time"])
df.describe()

plt.figure(figsize=(12,6))
plt.plot(df["time"], df["temperature"])
plt.title("Hourly Temperature - Delhi")
plt.xlabel("Time")
plt.ylabel("Temperature (°C)")
plt.grid(True)
plt.show()

df.to_csv("delhi_weather.csv", index=False)
print("Data saved as delhi_weather.csv")

def collect_weather(latitude, longitude):
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": "temperature_2m",
    }
    response = requests.get(url, params=params)
    data = response.json()

    df = pd.DataFrame({
        "time": data["hourly"]["time"],
        "temperature": data["hourly"]["temperature_2m"]
    })

    return df

df = collect_weather(28.6139, 77.2090)
df.tail()